on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

name: Publish NPM package
jobs:
  install:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: install
        run: npm install
      - name: build
        run: npm run build
      #- name: print diff if failed
      #  if: ${{ failure() }}
      #  run: cp dist/temp/decentraland-ecs-utils.api.md report/decentraland-ecs-utils.api.md && git diff
      - name: Publish
        uses: decentraland/oddish-action@0074f2d535c43b5c83f136525304a6277166d77f # @master
        with:
          #cwd: ./dist
          access: public # 'public' to deploy @scoped/packages
