on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

name: Publish NPM package
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # @v4.3.0
      - name: Use Node.js 24
        uses: actions/setup-node@v1
        with:
          node-version: '24'
      - name: install
        run: npm install
      - name: build
        run: npm run build
      #- name: print diff if failed
      #  if: ${{ failure() }}
      #  run: cp dist/temp/decentraland-ecs-utils.api.md report/decentraland-ecs-utils.api.md && git diff
      - name: upgrade npm for Trusted Publishing
        run: corepack install -g npm@11 && npm --version
      - name: Publish
        uses: decentraland/oddish-action@0074f2d535c43b5c83f136525304a6277166d77f # @master
        with:
          #cwd: ./dist
          access: public # 'public' to deploy @scoped/packages
        env:
